shared:
    image: node:18
    annotations:
        publish: &publish
            steps:
                - install: npm install screwdriver-template-main
                - publish: ./node_modules/.bin/pipeline-template-publish
jobs:
    publish-valid:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-init-pipeline-template.yaml
    publish-invalid:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-invalid-pipeline-template.yaml
